/// <reference types="vite/client" />

/**
 * Generated by the `homestead:discovered-apps` Vite plugin (see
 * `vite/discovered-apps.ts`): every `app.homestead.ts` found under the
 * project's app directories, as `[absolute path, imported module]` pairs in
 * registration order. `assertDiscoveredApp` narrows each module.
 */
declare module 'virtual:homestead-discovered-apps' {
  const discovered: [string, unknown][];
  export default discovered;
}
