import { Transport } from './transport';

export interface ListOptions {
  filter?: string;
  maxPageSize?: number;
}

export interface ListPageOptions extends ListOptions {
  pageToken?: string;
}

export interface Page<T> {
  results: T[];
  nextPageToken?: string;
}

interface ListResponseRaw<T> {
  results?: T[];
  next_page_token?: string;
}

/**
 * Base class for all generated resource collections. Holds the
 * transport, the parent URL prefix (empty for root resources), and
 * the resource's plural URL segment. Subclasses generated by the
 * codegen narrow the body/result types and add accessors for
 * parented children.
 */
export class ResourceCollection<T, CreateBody = Partial<T>, UpdateBody = Partial<T>> {
  constructor(
    readonly transport: Transport,
    /** Alternating `[plural, id, plural, id, ...]` parent segments. */
    readonly parentPath: readonly string[],
    readonly plural: string,
  ) {}

  /** URL of the collection itself: `/parents.../plural`. */
  protected collectionPath(): string {
    if (!this.parentPath.length) return `/${this.plural}`;
    return `/${this.parentPath.join('/')}/${this.plural}`;
  }

  /** URL of a single item: `/parents.../plural/{id}`. */
  protected itemPath(id: string): string {
    return `${this.collectionPath()}/${encodeURIComponent(id)}`;
  }

  async listPage(opts: ListPageOptions = {}): Promise<Page<T>> {
    const raw = await this.transport.request<ListResponseRaw<T>>(
      this.collectionPath(),
      {
        query: {
          max_page_size: opts.maxPageSize ?? 100,
          page_token: opts.pageToken,
          filter: opts.filter,
        },
      },
    );
    return {
      results: raw.results ?? [],
      nextPageToken: raw.next_page_token || undefined,
    };
  }

  /** Auto-paginate and return all records. Today's `list()` semantics. */
  async list(opts: ListOptions = {}): Promise<T[]> {
    const out: T[] = [];
    let pageToken: string | undefined;
    do {
      const page = await this.listPage({ ...opts, pageToken });
      out.push(...page.results);
      pageToken = page.nextPageToken;
    } while (pageToken);
    return out;
  }

  async *iterate(opts: ListOptions = {}): AsyncIterableIterator<T> {
    let pageToken: string | undefined;
    do {
      const page = await this.listPage({ ...opts, pageToken });
      for (const item of page.results) yield item;
      pageToken = page.nextPageToken;
    } while (pageToken);
  }

  get(id: string): Promise<T> {
    return this.transport.request<T>(this.itemPath(id));
  }

  create(body: CreateBody | FormData): Promise<T> {
    return this.transport.request<T>(this.collectionPath(), {
      method: 'POST',
      body: body as unknown,
    });
  }

  update(id: string, body: UpdateBody | FormData): Promise<T> {
    return this.transport.request<T>(this.itemPath(id), {
      method: 'PATCH',
      body: body as unknown,
      mergePatch: !(body instanceof FormData),
    });
  }

  delete(id: string): Promise<void> {
    return this.transport.request<void>(this.itemPath(id), { method: 'DELETE' });
  }

  /**
   * Invoke a custom method (AEP-136). When `id` is null the method is
   * invoked on the collection (e.g. `/users/:login`); otherwise on a
   * single item (e.g. `/gift-cards/{id}:download`).
   */
  customMethod<R = unknown>(
    id: string | null,
    method: string,
    body?: unknown,
  ): Promise<R> {
    const target = id == null ? this.collectionPath() : this.itemPath(id);
    return this.transport.request<R>(`${target}:${method}`, {
      method: 'POST',
      body: body ?? {},
    });
  }

  /**
   * Custom-method variant that returns the raw `Response` — needed for
   * binary payloads like `:download` that don't round-trip through JSON.
   */
  customMethodRaw(
    id: string | null,
    method: string,
    body?: unknown,
  ): Promise<Response> {
    const target = id == null ? this.collectionPath() : this.itemPath(id);
    return this.transport.request<Response>(`${target}:${method}`, {
      method: 'POST',
      body: body ?? {},
      raw: true,
    });
  }
}
