// AUTO-GENERATED by scripts/gen-embedded.ts for `bun build --compile`.
//
// The committed version is a stub (all null) so that running from source uses
// repo paths (see embed.ts). At release build time the generator overwrites
// this file with real `import … with { type: 'file' }` statements that Bun
// bakes into the binary, then the Makefile restores the stub.
//
// Do not edit by hand.

/** Path to the embedded native aepbase binary (in Bun's virtual FS), or null. */
export const aepbasePath: string | null = null;

/** Map of SPA-relative path → embedded file path, or null when not embedded. */
export const spaFiles: Readonly<Record<string, string>> | null = null;
