#!/usr/bin/env bun
// Generate packages/homestead-cli/src/embedded.generated.ts with real
// `import … with { type: 'file' }` statements so `bun build --compile` bakes the
// aepbase binary and the built SPA into the binary. (The sidecar is bundled as
// JS and served in-process, so it isn't embedded as a binary.)
//
// Usage:
//   bun scripts/gen-embedded.ts --aepbase <path> --dist <dir>
//   bun scripts/gen-embedded.ts --restore
//
// The Makefile runs this before compiling and restores the committed stub
// afterwards, so the generated form never lands in git.
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const GEN_DIR = resolve(import.meta.dir, '..', 'packages', 'homestead-cli', 'src');
const OUT = join(GEN_DIR, 'embedded.generated.ts');

const STUB = `// AUTO-GENERATED by scripts/gen-embedded.ts for \`bun build --compile\`.
//
// The committed version is a stub (all null) so that running from source uses
// repo paths (see embed.ts). At release build time the generator overwrites
// this file with real \`import … with { type: 'file' }\` statements that Bun
// bakes into the binary, then the Makefile restores the stub.
//
// Do not edit by hand.

/** Path to the embedded native aepbase binary (in Bun's virtual FS), or null. */
export const aepbasePath: string | null = null;

/** Map of SPA-relative path → embedded file path, or null when not embedded. */
export const spaFiles: Readonly<Record<string, string>> | null = null;
`;

// `--restore` resets the committed stub (Makefile runs it after compiling).
if (process.argv.includes('--restore')) {
  writeFileSync(OUT, STUB);
  console.log(`restored stub ${OUT}`);
  process.exit(0);
}

function arg(name: string): string {
  const i = process.argv.indexOf(`--${name}`);
  if (i === -1 || !process.argv[i + 1]) {
    throw new Error(`missing --${name} <path>`);
  }
  return resolve(process.argv[i + 1]);
}

/** Relative import specifier from the generated file to an asset. */
function spec(absPath: string): string {
  const rel = relative(GEN_DIR, absPath).replaceAll('\\', '/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function walk(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full, base));
    else out.push(full);
  }
  return out;
}

const aepbase = arg('aepbase');
const distDir = arg('dist');

const distFiles = walk(distDir).sort();
const imports: string[] = [
  `import _aepbase from ${JSON.stringify(spec(aepbase))} with { type: 'file' };`,
];
const spaEntries: string[] = [];
distFiles.forEach((file, i) => {
  const id = `_spa${i}`;
  imports.push(`import ${id} from ${JSON.stringify(spec(file))} with { type: 'file' };`);
  const rel = relative(distDir, file).replaceAll('\\', '/');
  spaEntries.push(`  ${JSON.stringify(rel)}: ${id},`);
});

const body = `// AUTO-GENERATED by scripts/gen-embedded.ts — do not edit or commit.
${imports.join('\n')}

export const aepbasePath: string | null = _aepbase;
export const spaFiles: Readonly<Record<string, string>> | null = {
${spaEntries.join('\n')}
};
`;

writeFileSync(OUT, body);
console.log(`wrote ${OUT} (${distFiles.length} SPA files + aepbase)`);
