#!/usr/bin/env bash
# Homestead one-line installer.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/rambleraptor/homestead/main/scripts/install.sh | bash
#
# Environment overrides:
#   HOMESTEAD_DIR     Target directory (default: ./homestead)
#   HOMESTEAD_REPO    Git URL          (default: https://github.com/rambleraptor/homestead.git)
#   HOMESTEAD_BRANCH  Branch to clone  (default: main)
#   AEPBASE_PORT      Port aepbase binds while bootstrapping (default: 8090)
#
# The installer is non-interactive. It clones the repo, installs npm
# workspaces, builds aepbase, runs it once to capture the bootstrap
# superuser credentials, writes them into frontend/.env.local, and then
# prints the two commands you need to bring the stack up.

set -euo pipefail

HOMESTEAD_DIR="${HOMESTEAD_DIR:-./homestead}"
HOMESTEAD_REPO="${HOMESTEAD_REPO:-https://github.com/rambleraptor/homestead.git}"
HOMESTEAD_BRANCH="${HOMESTEAD_BRANCH:-main}"
AEPBASE_PORT="${AEPBASE_PORT:-8090}"

if [[ -t 1 ]]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GRN=$'\033[32m'; YLW=$'\033[33m'; RST=$'\033[0m'
else
  BOLD=''; DIM=''; RED=''; GRN=''; YLW=''; RST=''
fi
log()  { printf '%s==>%s %s\n' "$BOLD" "$RST" "$*"; }
warn() { printf '%s==>%s %s\n' "$YLW" "$RST" "$*" >&2; }
fail() { printf '%serror:%s %s\n' "$RED" "$RST" "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || fail "missing prerequisite: $1${2:+ — $2}"; }

# 1. Prerequisites -------------------------------------------------------
log "Checking prerequisites"
need git
need node "install Node.js 20+ from https://nodejs.org"
need npm
need go   "install Go 1.22+ from https://go.dev/dl"

node_major="$(node -p 'process.versions.node.split(".")[0]')"
[[ "$node_major" -ge 20 ]] || fail "Node.js 20+ required (have $(node -v))"

go_ver="$(go version | awk '{print $3}')"
go_minor="$(printf '%s\n' "$go_ver" | sed -E 's/^go1\.([0-9]+).*$/\1/')"
[[ "$go_minor" =~ ^[0-9]+$ && "$go_minor" -ge 22 ]] \
  || fail "Go 1.22+ required (have $go_ver)"

# 2. Clone --------------------------------------------------------------
if [[ -e "$HOMESTEAD_DIR" && -n "$(ls -A "$HOMESTEAD_DIR" 2>/dev/null || true)" ]]; then
  fail "$HOMESTEAD_DIR exists and is not empty — set HOMESTEAD_DIR or remove it"
fi

log "Cloning $HOMESTEAD_REPO (branch $HOMESTEAD_BRANCH) into $HOMESTEAD_DIR"
git clone --depth 1 --branch "$HOMESTEAD_BRANCH" "$HOMESTEAD_REPO" "$HOMESTEAD_DIR"
cd "$HOMESTEAD_DIR"

# 3. npm workspaces -----------------------------------------------------
log "Installing npm workspaces (this can take a minute)"
npm install --no-audit --no-fund

# 4. Build aepbase ------------------------------------------------------
log "Building aepbase"
( cd aepbase && ./install.sh )

# 5. Bootstrap aepbase and capture creds --------------------------------
log "Starting aepbase to capture the bootstrap superuser credentials"
AEPBASE_LOG="$(mktemp -t homestead-aepbase.XXXXXX)"

( cd aepbase && AEPBASE_PORT="$AEPBASE_PORT" ./run.sh ) >"$AEPBASE_LOG" 2>&1 &
AEPBASE_PID=$!

cleanup() {
  if kill -0 "$AEPBASE_PID" 2>/dev/null; then
    kill "$AEPBASE_PID" 2>/dev/null || true
    wait "$AEPBASE_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT

listening=0
for _ in $(seq 1 60); do
  if grep -q "aepbase listening on" "$AEPBASE_LOG" 2>/dev/null; then
    listening=1
    break
  fi
  if ! kill -0 "$AEPBASE_PID" 2>/dev/null; then
    cat "$AEPBASE_LOG" >&2
    fail "aepbase exited before reporting it was listening"
  fi
  sleep 0.5
done
[[ "$listening" -eq 1 ]] || { cat "$AEPBASE_LOG" >&2; fail "aepbase did not start within 30s"; }

if ! grep -q "DEFAULT SUPERUSER CREATED" "$AEPBASE_LOG"; then
  fail "aepbase booted but did not create a new superuser — aepbase/data already contains users. Remove aepbase/data and re-run, or set AEPBASE_ADMIN_EMAIL / AEPBASE_ADMIN_PASSWORD in frontend/.env.local manually."
fi

SUPERUSER_EMAIL="$(awk '/^[[:space:]]*Email:/    {print $2; exit}' "$AEPBASE_LOG")"
SUPERUSER_PASSWORD="$(awk '/^[[:space:]]*Password:/ {print $2; exit}' "$AEPBASE_LOG")"
[[ -n "$SUPERUSER_EMAIL" && -n "$SUPERUSER_PASSWORD" ]] \
  || fail "failed to parse superuser credentials from $AEPBASE_LOG"

cleanup
trap - EXIT
rm -f "$AEPBASE_LOG"

# 6. Write frontend/.env.local -----------------------------------------
log "Writing frontend/.env.local"
ENV_FILE="frontend/.env.local"
[[ -e "$ENV_FILE" ]] && cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
(
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh
AEPBASE_URL=http://127.0.0.1:$AEPBASE_PORT
AEPBASE_ADMIN_EMAIL=$SUPERUSER_EMAIL
AEPBASE_ADMIN_PASSWORD=$SUPERUSER_PASSWORD
EOF
)

# 7. Hand-off ----------------------------------------------------------
INSTALL_DIR="$(pwd)"
cat <<EOF

${GRN}✓ Homestead is installed at ${INSTALL_DIR}${RST}

Superuser credentials (also stored in ${ENV_FILE}):
  Email:    ${SUPERUSER_EMAIL}
  Password: ${SUPERUSER_PASSWORD}
  ${DIM}Change this password the first time you log in.${RST}

Next steps — open two terminals:

  ${BOLD}Terminal 1${RST}  cd ${INSTALL_DIR}/aepbase && ./run.sh
  ${BOLD}Terminal 2${RST}  cd ${INSTALL_DIR}/frontend && npm run dev

Then open http://localhost:3000 and log in.

To customize which feature modules ship, edit
  ${INSTALL_DIR}/frontend/homestead.config.ts
See docs/SELF_HOSTING.md for the full self-hosting walkthrough.
EOF
